[package]
name = "blinksy-esp"
version = "0.11.0"
edition = "2021"

rust-version.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["blinksy", "embedded", "no-std", "esp32"]
categories.workspace = true

[dependencies]
blinksy = { path = "../../blinksy", version = "0.11" }
esp-hal = { version = "~1.0", features = ["unstable"] }
esp-bootloader-esp-idf = { version = "0.4.0" }
esp-backtrace = {version = "0.18.1", optional = true, features = ["panic-handler"] }
esp-println = { version = "0.16.0", optional = true }
defmt = { version = "1.0.1", optional = true }
heapless = "0.9.1"
num-traits = { version = "0.2", default-features = false, features = ["libm"] }

[features]
default = [
  "backtrace",
  "defmt"
]
async = [
  "blinksy/async",
]
defmt = [
  "dep:defmt",
  "dep:esp-println",
  "blinksy/defmt",
  "esp-hal/defmt",
  "esp-println?/defmt-espflash",
  "esp-backtrace?/defmt",
  "esp-bootloader-esp-idf/defmt"
]
backtrace = [
  "dep:esp-backtrace",
]
println = [
  "dep:esp-println",
  "esp-backtrace?/println"
]

# Chip Support Feature Flags
# Target the ESP32-C2.
esp32c2 = [
  "esp-hal/esp32c2",
  "esp-println?/esp32c2",
  "esp-backtrace?/esp32c2",
  "esp-bootloader-esp-idf/esp32c2",
]
# Target the ESP32-C3.
esp32c3 = [
  "esp-hal/esp32c3",
  "esp-println?/esp32c3",
  "esp-backtrace?/esp32c3",
  "esp-bootloader-esp-idf/esp32c3",
]
# Target the ESP32-C6.
esp32c6 = [
  "esp-hal/esp32c6",
  "esp-println?/esp32c6",
  "esp-backtrace?/esp32c6",
  "esp-bootloader-esp-idf/esp32c6",
]
# Target the ESP32-H2.
esp32h2 = [
  "esp-hal/esp32h2",
  "esp-println?/esp32h2",
  "esp-backtrace?/esp32h2",
  "esp-bootloader-esp-idf/esp32h2",
]
# Target the ESP32.
esp32 = [
  "esp-hal/esp32",
  "esp-println?/esp32",
  "esp-backtrace?/esp32",
  "esp-bootloader-esp-idf/esp32",
]
# Target the ESP32-S2.
esp32s2 = [
  "esp-hal/esp32s2",
  "esp-println?/esp32s2",
  "esp-backtrace?/esp32s2",
  "esp-bootloader-esp-idf/esp32s2",
]
# Target the ESP32-S3.
esp32s3 = [
  "esp-hal/esp32s3",
  "esp-println?/esp32s3",
  "esp-backtrace?/esp32s3",
  "esp-bootloader-esp-idf/esp32s3",
]

[package.metadata.docs.rs]
default-target = "riscv32imac-unknown-none-elf"
features = ["esp32c6", "async"]
